spring.application.name=bonahr-backend

spring.profiles.active=dev

bonahr.jwt.secret=4qWNH7bKS+DPmW0gbdhogdb2GLVyv3iFEERlT6S5QhqPfSGL38MMIF+RYCw0m9Jsl2sseYEeP9NC8p0nX+roEw==
bonahr.jwt.expiration-minutes=60
bonahr.jwt.issuer=bonahr-api

spring.datasource.url=jdbc:postgresql://localhost:5432/bonahr
spring.datasource.username=bonahr
spring.datasource.password=Pass0rd

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
