spring.application.name=bonahr-backend


spring.datasource.url=jdbc:postgresql://localhost:5432/bonahr
spring.datasource.username=bonahr
spring.datasource.password=Pass0rd

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
